site_name: Первая лабораторная работа
site_author: Тимаков Егор K3341
site_url: localhost:9090

nav:
  -Главная: index.md
  -Первое задание: Task1
  -Второе задание: Task2
  -Третье задание: Task3
  -Четвертое задание: Task4
  -Пятое задание: Task5

theme:
  name: material